Fibs/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fibs.Data;
using Fibs.Models;
using Fibs.DataAccess.Repository;
using Fibs.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace Fibs.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private UserManager<ApplicationUser> _userManager;
        public ProductsController(IUnitOfWork unitOfWork, UserManager<ApplicationUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            var products = await _unitOfWork.Products.GetAll();
            return View(products);
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            var product = await _unitOfWork.Products.GetFirstOrDefault(m => m.Id == id);
            bool isFavorite = await _unitOfWork.FavoriteProducts.IsFavorite(_userManager.GetUserId(User),id);
            ViewData["isFavorite"] = isFavorite;
            if (product == null)
                return NotFound();
            return View(product);
        }

        // GET: Products/Create
        [Authorize(Roles ="Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,Size,NoOfPieces,Material,Details,FavoritesNo")] Product product)
        {
            await _unitOfWork.Products.Add(product, Request.Form.Files);
            await _unitOfWork.SaveAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Products/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            var product = await _unitOfWork.Products.GetFirstOrDefault(m => m.Id == id);
            if (product == null)
                return NotFound();
            return View(product);
        }

        // POST: Products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(Guid id, Product product)
        {
            try
            {
                await _unitOfWork.Products.Update(product, Request.Form.Files);
                await _unitOfWork.SaveAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                return View(product);
            }
        }

        // GET: Products/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            var product = await _unitOfWork.Products.GetFirstOrDefault(m=>m.Id==id);
            _unitOfWork.Products.Remove(product);
            await _unitOfWork.SaveAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Fibs/Controllers/ShoppingBagController.cs
using Fibs.DataAccess.Repository.IRepository;
using Fibs.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Fibs.Controllers
{
    [Authorize]
    public class ShoppingBagController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<ApplicationUser> _userManager;
        public ShoppingBagController(IUnitOfWork unitOfWork, UserManager<ApplicationUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            List<ShoppingBag> bags = await _unitOfWork.ShoppingBags.GetBag(userId);
            return View(bags);
        }
        public async Task<IActionResult> Add(Guid Id,string ControllerName)
        {
            await _unitOfWork.ShoppingBags.AddProductToBag(_userManager.GetUserId(User), Id);
            await _unitOfWork.SaveAsync();
            return RedirectToAction("Index",ControllerName);
        }
        public async Task<IActionResult> Delete(Guid Id)
        {
            var bag = await _unitOfWork.ShoppingBags.GetFirstOrDefault(m => m.Id == Id);
            _unitOfWork.ShoppingBags.Remove(bag);
            await _unitOfWork.SaveAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> ChangeQuantity(Guid Id , int Count)
        {
            var bag = await _unitOfWork.ShoppingBags.GetFirstOrDefault(m => m.Id == Id);
            bag.count = Count;
            await _unitOfWork.SaveAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Checkout()
        {
            await _unitOfWork.ShoppingBags.Checkout(_userManager.GetUserId(User));
            var bags = await _unitOfWork.ShoppingBags.GetBag(_userManager.GetUserId(User));
            manageNumberOfProducts(bags);
            await _unitOfWork.SaveAsync();
            return RedirectToAction("Index");
        }
        private void manageNumberOfProducts(List<ShoppingBag> bags)
        {
            foreach(var bag in bags)
            {
                bag.Product.NoOfPieces-=bag.count;
            }
        }
    }
}

Fibs/Views/ShoppingBag/Index.cshtml
@model List<Fibs.Models.ShoppingBag>

@{
    ViewData["Title"] = "Index";
}
<style>
    .btn-light, .btn-light:hover {
        border: 1px solid #333;
    }
</style>
<section class="row g-4 p-5">
    @* Shopping cart section*@
    <section class="col-md-5">
        <h1 style="font-weight:500">Shopping Cart</h1>
        <p class="lead m-0">
            <a asp-controller="Products" asp-action="Index" class="grey-link">Store</a> /
            <a asp-controller="ShoppingBag" asp-action="Index" class="grey-link">Shopping Cart</a>
        </p>
        @foreach(var bag in Model){
            <div class="product row my-4 align-items-center" style="font-weight:500">
                <img src="data:image/*;base64,@Convert.ToBase64String(bag.Product.Picture)" class="col-4">
                <div class="col-8">
                    <div class="d-flex justify-content-between">
                        <h5 style="font-weight:600">@bag.Product.Name</h5>
                        <a asp-controller="ShoppingBag" asp-action="Delete" asp-route-Id="@bag.Id" class="grey-link"><i class="bi bi-x text-grey"></i></a>
                    </div>
                    <p class="grey-link">Size: @bag.Product.Size</p>
                    
                        <form asp-action="ChangeQuantity" method="post">
                            <div class="d-flex justify-content-between">
                                <p>
                                    Qty:
                                    <input name="Count" type="number" class="form-control w-50 d-inline-block" value=@bag.count min="0">
                                </p>
                                <p>$@bag.Product.Price</p>
                            </div>
                            <input type="hidden" name="Id" value=@bag.Id class="form-control" placeholder="Count" />
                            <div class="form-group my-3">
                                <input type="submit" class="btn btn-primary form-control" />
                            </div>
                    </form>
                </div>
            </div>
        }

        <hr />
        <div class="d-flex justify-content-between my-5">
            <h2 style="font-weight:500">Total</h2>
            <h2 style="font-weight:500">$@Model.Sum(m=>m.Product.Price*m.count)</h2>
        </div>
    </section>
    <section class="col-md-7 p-5">
        <h1 style="font-weight:500" class="mt-5">Checkout</h1>
        <p class="lead mb-5">Enter your full address. This address will be used to send your order to you</p>
        <div class="form-group my-3">
            <input type="text" placeholder="Your Full Address" class="form-control p-3" />
        </div>
        <div class="form-group my-3">
            <a asp-action="Checkout" class="btn btn-dark form-control p-3">Checkout</a>
        </div>
        <p>Looking for More? 
            <a asp-action="Index" asp-controller="Products">Continue Shopping</a>
        </p>
    </section>
</section>