Fibs/Controllers/FavoriteProductController.cs
using Fibs.DataAccess.Repository.IRepository;
using Fibs.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Fibs.Controllers
{
    [Authorize]
    public class FavoriteProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<ApplicationUser> _userManager;
        public FavoriteProductController(IUnitOfWork unitOfWork,UserManager<ApplicationUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            var products = await _unitOfWork.FavoriteProducts.GetUsersFavorites(userId);
            return View(products);
        }
        public async Task<IActionResult> AddToFavorites(Guid Id)
        {
            await manageProductsFavoritesNumber(Id);
            await _unitOfWork.FavoriteProducts.Toggle(_userManager.GetUserId(User), Id);
            await _unitOfWork.SaveAsync();
            return RedirectToAction("Details","Products",new {id = Id});
        }

        private async Task manageProductsFavoritesNumber(Guid productId)
        {
            if (await _unitOfWork.FavoriteProducts.IsFavorite(_userManager.GetUserId(User), productId))
                await _unitOfWork.Products.DecreaseProductFavorites(productId);
            else
                await _unitOfWork.Products.IncreaseProductFavorites(productId);
        }
    }
}

Fibs/Controllers/ShoppingBagController.cs
using Fibs.DataAccess.Repository.IRepository;
using Fibs.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Fibs.Controllers
{
    [Authorize]
    public class ShoppingBagController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<ApplicationUser> _userManager;
        public ShoppingBagController(IUnitOfWork unitOfWork, UserManager<ApplicationUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            List<ShoppingBag> bags = await _unitOfWork.ShoppingBags.GetBag(userId);
            return View(bags);
        }
        public async Task<IActionResult> Add(Guid Id,string ControllerName)
        {
            await _unitOfWork.ShoppingBags.AddProductToBag(_userManager.GetUserId(User), Id);
            await _unitOfWork.SaveAsync();
            return RedirectToAction("Index",ControllerName);
        }
        public async Task<IActionResult> Delete(Guid Id)
        {
            var bag = await _unitOfWork.ShoppingBags.GetFirstOrDefault(m => m.Id == Id);
            _unitOfWork.ShoppingBags.Remove(bag);
            await _unitOfWork.SaveAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> ChangeQuantity(Guid Id , int Count)
        {
            var bag = await _unitOfWork.ShoppingBags.GetFirstOrDefault(m => m.Id == Id);
            bag.count = Count;
            await _unitOfWork.SaveAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Checkout()
        {
            await _unitOfWork.ShoppingBags.Checkout(_userManager.GetUserId(User));
            var bags = await _unitOfWork.ShoppingBags.GetBag(_userManager.GetUserId(User));
            manageNumberOfProducts(bags);
            await _unitOfWork.SaveAsync();
            return RedirectToAction("Index");
        }
        private void manageNumberOfProducts(List<ShoppingBag> bags)
        {
            foreach(var bag in bags)
            {
                bag.Product.NoOfPieces-=bag.count;
            }
        }
    }
}

Fibs/Views/FavoriteProduct/Index.cshtml
@model List<Fibs.Models.Product>

@{
    ViewData["Title"] = "Index";
}
<style>
    .card {
        border: 0px;
        cursor: pointer;
    }

    .product-img {
        height: 270px;
        background-size: 100% 100%;
        background-position: 50% 50%;
    }

        .product-img .hover {
            height: 100%;
            display: none !important;
        }

        .product-img:hover .hover {
            display: flex !important;
            width: 100%;
            background-color: white;
            opacity: 0.7;
        }

    p {
        margin: 0;
    }

    .btn-light, .btn-light:hover {
        border: 1px solid #333;
    }
</style>
@*Favorites List*@

<h2 style="font-weight:500">My Favorites</h2>
<p class="lead">
    <a asp-controller="Products" asp-action="Index" class="grey-link">Store</a> / 
    <a asp-controller="FavoriteProduct" asp-action="Index" class="grey-link">Favorites</a>
</p>
@if (Model.Count == 0)
{
    <h4 class="my-5">
        you don't have any favorites yet go to
        <a asp-controller="Products" asp-action="Index">Store</a>
        and make some Favorites
    </h4>
}
<div class="row align-items-center justify-content-md-start justify-content-sm-center g-4">
    @foreach (var item in Model)
    {
        <div class="card col-lg-3 col-md-4 col-sm-6 col-10 position-realtive"
         onclick="window.location.href=window.location.origin.concat('/Products/Details/@item.Id')">
            <div class="product-img position-relative"
             style="background-image:url('data:image/*;base64,@Convert.ToBase64String(item.Picture)'">
                <div class="hover flex-column align-items-center justify-content-center p-5">
                    <a class="btn btn-light" asp-controller="ShoppingBag" asp-action="Add" asp-route-Id=@item.Id asp-route-ControllerName="FavoriteProduct">Add To Bag</a>
                    <div class="d-flex align-items-center justify-content-center m-3">
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="btn btn-warning m-2" asp-controller="Products" asp-action="Edit" asp-route-Id=@item.Id>Edit</a>
                            <a class="btn btn-danger m-2" asp-controller="Products" asp-action="Delete" asp-route-Id=@item.Id>Delete</a>
                        }
                    </div>
                </div>
            </div>
            <div class="card-body">
                <p class="fw-bold">@item.Name</p>
                <p class="lead">$ @item.Price</p>
            </div>
        </div>
    }
</div>